# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Luau' do
pod 'React', :subspecs => [
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
]
end

target 'LuauTests' do
pod 'React', :subspecs => [
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTWebSocket',
]
end

